import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import { useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import Carousel from "@/components/Carousel";
import Services from "@/components/Services";
import Properties from "@/components/Properties";
import Task from "@/components/Task";
import Feedback from "@/components/Feedback";
import Footer from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min");
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Carousel />
      <div className={"container"}>
        <Services />
        <Properties />
        <Task />
        <Feedback />
      </div>
      <div className="bg-black">
        <Footer />
      </div>
    </>
  );
}
